### PR TITLE
Adding WorkAdventure to the list of Open-source Social VR

### PR DESCRIPTION
**Pull request by moufmouf**
Hey!

Most of the list is about 3D universes with a virtual reality headset, but there are a number of metaverses in the 2D world.

If your list is not only restricted to 3D worlds, I suggest adding WorkAdventure: https://workadventu.re

### CODE REVIEW

**Comment by madjin** [comment]
Hiya!

This is a great suggestion, there's a few other 2D projects I'd like to include also. I think I will make a category for them under the 3D ones :)

Btw WorkAdventure looks cool! - few of us are exploring methods to streamline the conversion 3D avatars into sprite sheets
PureRef_xwQyjpo8DW

**Comment by madjin** [comment]
added

**Comment by moufmouf** [comment]
Hey @madjin !

The 3D to 2D spritesheet is so cool! Do you have a reference or a link I could have a look at?

**Comment by madjin** [comment]
howdy, yeah try drag n dropping a vrm file (vroid studio / vroid hub to find one, https://hackmd.io/@XR/avatars to learn more) into webaverse (test here: https://app.webaverse.com/?src=.%2Fscenes%2Fgrid.scn) and go to settings and turn character settings to low, VRM -> sprite sheet generated

image

https://user-images.githubusercontent.com/32600939/163942704-613ed85b-4b52-442f-a019-eed2265f454d.mp4

code here: https://github.com/webaverse/app/blob/8ea9f59b28e0cbd5fa7b664e9011f15f6b620682/avatar-spriter.js

also have more notes here: https://hackmd.io/@XR/avatarlod

> Hey @madjin !
> 
> The 3D to 2D spritesheet is so cool! Do you have a reference or a link I could have a look at?

**Pull request closed without merging**
